# Generated by Django 5.0.7 on 2026-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kind',
            field=models.CharField(choices=[('product', 'Produto'), ('service', 'Serviço'), ('subscription', 'Assinatura')], default='product', max_length=20),
        ),
    ]
