# Generated by Django 5.0.7 on 2026-08-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='asaas_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
