# Generated by Django 5.0.7 on 2026-08-13 13:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_providerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, null=True, validators=[apps.core.validators.validate_image_url]),
        ),
    ]
