# Generated by Django 5.0.7 on 2026-08-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='publicprofile',
            name='bio',
        ),
    ]
