# Generated by Django 5.0.7 on 2026-08-04 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('providers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'prestador'}, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, default='', verbose_name='endereço')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='agendado para')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('quoted', 'Orçado'), ('approved', 'Aprovado'), ('concluded', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.service')),
            ],
            options={
                'verbose_name': 'Solicitação de Serviço',
                'verbose_name_plural': 'Solicitações de Serviços',
                'ordering': ['-created_at'],
            },
        ),
    ]
