# Generated by Django 5.0.7 on 2026-08-09 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_kind'),
        ('services', '0003_alter_service_base_price_alter_service_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_type', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='tipo de plano')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor do ciclo')),
                ('next_due_date', models.DateField(verbose_name='próximo vencimento')),
                ('asaas_subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='assinatura Asaas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plan', to='checkout.order', verbose_name='pedido de pagamento')),
                ('prestador', models.ForeignKey(blank=True, limit_choices_to={'role': 'prestador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans_as_provider', to=settings.AUTH_USER_MODEL, verbose_name='prestador atribuído')),
            ],
            options={
                'verbose_name': 'Plano de Manutenção',
                'verbose_name_plural': 'Planos de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='agendada para')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='services.maintenanceplan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'Visita de Manutenção',
                'verbose_name_plural': 'Visitas de Manutenção',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
