# Generated by Django 5.0.7 on 2026-08-13 13:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_slug_alter_servicecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True, validators=[apps.core.validators.validate_image_url], verbose_name='imagem'),
        ),
    ]
