# Generated by Django 5.0.7 on 2026-08-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='asaas_payment_link_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Id do paymentLink avulso; usado para reconciliar o pagamento via webhook.', max_length=120, verbose_name='link de pagamento (Asaas)'),
        ),
    ]
