# Generated by Django 5.0.7 on 2026-08-17 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicerequest_asaas_payment_link_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('plan_type', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='tipo de plano')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço por ciclo')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'Plano de Manutenção (catálogo)',
                'verbose_name_plural': 'Planos de Manutenção (catálogo)',
                'ordering': ['ordering', 'value'],
            },
        ),
    ]
