# Generated by Django 5.0.7 on 2026-08-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_seed_maintenance_plan_templates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maintenanceplantemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plan_type',), name='uniq_services_active_plan_type'),
        ),
    ]
