# Generated by Django 5.0.7 on 2026-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_maintenanceplantemplate_uniq_services_active_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='affiliate_ref_code',
            field=models.CharField(blank=True, default='', help_text='Código do afiliado que indicou esta solicitação (cookie ref).', max_length=20, verbose_name='código de afiliado (referral)'),
        ),
    ]
