# Generated by Django 5.0.7 on 2026-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_add_affiliate_ref_code_to_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplantemplate',
            name='affiliate_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Override da comissão do afiliado para assinaturas deste plano (ex.: 0.15 = 15%)', max_digits=5, null=True, verbose_name='comissão do afiliado'),
        ),
        migrations.AddField(
            model_name='service',
            name='affiliate_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Override da comissão do afiliado para este serviço (ex.: 0.15 = 15%)', max_digits=5, null=True, verbose_name='comissão do afiliado'),
        ),
    ]
