# Generated by Django 5.0.7 on 2026-08-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_maintenanceplantemplate_affiliate_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='endereço'),
        ),
    ]
