# Generated by Django 5.0.7 on 2026-09-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_servicerequest_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='client',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='maintenancevisit',
            name='plan',
        ),
        migrations.DeleteModel(
            name='MaintenancePlanTemplate',
        ),
        migrations.DeleteModel(
            name='MaintenancePlan',
        ),
        migrations.DeleteModel(
            name='MaintenanceVisit',
        ),
    ]
