# Generated by Django 5.0.7 on 2026-08-20 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('checkout', '0003_alter_order_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Indicação', 'verbose_name_plural': 'Indicações'},
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('affiliate', 'order'), name='uniq_referral_affiliate_order'),
        ),
    ]
