# Generated by Django 5.0.7 on 2026-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('store_enabled', models.BooleanField(default=True, verbose_name='loja habilitada')),
                ('services_enabled', models.BooleanField(default=True, verbose_name='serviços habilitados')),
                ('affiliates_enabled', models.BooleanField(default=True, verbose_name='programa de afiliados habilitado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
