# Generated by Django 5.0.7 on 2026-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_enabled',
            field=models.BooleanField(default=True, verbose_name='manutenção habilitada'),
        ),
    ]
