# Generated by Django 5.0.7 on 2026-08-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_maintenance_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='provider_registration_enabled',
            field=models.BooleanField(default=True, verbose_name='cadastro de prestadores habilitado'),
        ),
    ]
