# Generated by Django 5.0.7 on 2026-09-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_provider_registration_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='store_enabled',
        ),
    ]