# Generated by Django 5.0.7 on 2026-09-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesettings_store_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='maintenance_enabled',
        ),
    ]
