# Generated by Django 5.0.7 on 2026-08-14 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_kind'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='uniq_payments_provider_external_id'),
        ),
    ]
