# Generated by Django 5.0.7 on 2026-08-14 21:30

from django.db import migrations, models


def backfill_kind(apps, schema_editor):
    """Marca como `checkout` as transações de Checkout hosted já existentes.

    Antes do campo `kind`, checkouts eram identificados por
    `raw_payload__contains='"checkout"'` no `sync_payments`. O backfill preserva
    o discriminador para que a reconciliação continue ignorando-os.
    """
    Transaction = apps.get_model("payments", "Transaction")
    Transaction.objects.filter(raw_payload__contains='"checkout"').update(kind="checkout")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_uniq_payments_provider_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('payment', 'Pagamento'), ('checkout', 'Checkout')], default='payment', max_length=20),
        ),
        migrations.RunPython(backfill_kind, reverse_code=migrations.RunPython.noop),
    ]
