# Generated by Django 5.0.7 on 2026-08-13 13:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(validators=[apps.core.validators.validate_image_url]),
        ),
    ]
