# Generated by Django 5.0.7 on 2026-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Override da comissão do afiliado para este produto (ex.: 0.15 = 15%)', max_digits=5, null=True),
        ),
    ]
