# Generated by Django 5.0.7 on 2026-08-08 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=160, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='video',
            field=models.URLField(blank=True, default='', verbose_name='vídeo'),
        ),
    ]
