# Generated by Django 5.0.7 on 2026-08-13 13:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.URLField(blank=True, null=True, validators=[apps.core.validators.validate_image_url], verbose_name='imagem'),
        ),
    ]
